// lib/services/export_service.dart
// ✨ Font-safe PDF export — uses Google Fonts for Unicode support
// No emoji in PDF (PDF doesn't support emoji glyphs reliably)

import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:google_fonts/google_fonts.dart';
import '../models/message.dart';
import '../theme/persona_theme.dart';

class ExportService {

  // ── Load fonts once ────────────────────────────────────────────────────────
  static pw.Font? _regular;
  static pw.Font? _bold;

  static Future<void> _loadFonts() async {
    if (_regular != null) return; // already loaded
    _regular = await PdfGoogleFonts.nunitoRegular();
    _bold    = await PdfGoogleFonts.nunitoBold();
  }

  // ── Export as PDF ──────────────────────────────────────────────────────────
  static Future<void> exportAsPdf({
    required BuildContext context,
    required List<Message> messages,
    required PersonaTheme persona,
    required String chatTitle,
  }) async {
    try {
      _showLoading(context);
      await _loadFonts();
      final Uint8List bytes = await _generatePdfBytes(
        messages: messages,
        persona: persona,
        chatTitle: chatTitle,
      );
      if (context.mounted) Navigator.pop(context); // close loading

      await Printing.sharePdf(
        bytes: bytes,
        filename: 'Chattr_${chatTitle.replaceAll(' ', '_')}_'
            '${DateTime.now().millisecondsSinceEpoch}.pdf',
      );
    } catch (e) {
      if (context.mounted) {
        Navigator.pop(context);
        _showError(context, 'PDF export failed: $e');
      }
    }
  }

  // ── Preview PDF ────────────────────────────────────────────────────────────
  static Future<void> previewPdf({
    required BuildContext context,
    required List<Message> messages,
    required PersonaTheme persona,
    required String chatTitle,
  }) async {
    await _loadFonts();
    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => Scaffold(
          appBar: AppBar(
            title: const Text('PDF Preview'),
            actions: [
              IconButton(
                icon: const Icon(Icons.share_rounded),
                onPressed: () => exportAsPdf(
                  context: context,
                  messages: messages,
                  persona: persona,
                  chatTitle: chatTitle,
                ),
              ),
            ],
          ),
          body: PdfPreview(
            build: (format) => _generatePdfBytes(
              messages: messages,
              persona: persona,
              chatTitle: chatTitle,
            ),
            allowPrinting: false,   // avoid print plugin issues
            allowSharing: true,
            canChangePageFormat: false,
            pdfFileName: 'Chattr_$chatTitle.pdf',
          ),
        ),
      ),
    );
  }

  // ── Export as TXT ──────────────────────────────────────────────────────────
  static Future<void> exportAsTxt({
    required BuildContext context,
    required List<Message> messages,
    required PersonaTheme persona,
    required String chatTitle,
  }) async {
    try {
      final buffer = StringBuffer();

      buffer.writeln('=' * 50);
      buffer.writeln('CHATTR — ${chatTitle.toUpperCase()}');
      buffer.writeln('Persona: ${persona.name}');
      buffer.writeln('Exported: ${_formatDate(DateTime.now())}');
      buffer.writeln('Total messages: ${messages.length}');
      buffer.writeln('=' * 50);
      buffer.writeln();

      for (final msg in messages) {
        final sender = msg.isUser ? 'You' : persona.name;
        final time = _formatTime(msg.timestamp);
        buffer.writeln('[$time] $sender:');
        buffer.writeln(msg.text);
        if (msg.reactions.isNotEmpty) {
          buffer.writeln('Reactions: ${msg.reactions.join(' ')}');
        }
        buffer.writeln();
      }

      buffer.writeln('=' * 50);
      buffer.writeln('Generated by Chattr App');

      final dir = await getTemporaryDirectory();
      final filename =
          'Chattr_${chatTitle.replaceAll(' ', '_')}_'
          '${DateTime.now().millisecondsSinceEpoch}.txt';
      final file = File('${dir.path}/$filename');
      await file.writeAsString(buffer.toString());

      await Share.shareXFiles(
        [XFile(file.path)],
        subject: 'Chattr — $chatTitle',
        text: 'My chat export from Chattr',
      );
    } catch (e) {
      if (context.mounted) _showError(context, 'TXT export failed: $e');
    }
  }

  // ── PDF Generator ──────────────────────────────────────────────────────────
  static Future<Uint8List> _generatePdfBytes({
    required List<Message> messages,
    required PersonaTheme persona,
    required String chatTitle,
  }) async {
    await _loadFonts();

    final regular = _regular!;
    final bold    = _bold!;

    final pdf = pw.Document(
      title: 'Chattr — $chatTitle',
      author: 'Chattr App',
      theme: pw.ThemeData.withFont(
        base: regular,
        bold: bold,
      ),
    );

    final primary   = _toPdfColor(persona.primary);
    final secondary = _toPdfColor(persona.secondary);

    // ── Cover page ───────────────────────────────────────────────────────────
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.zero,
        build: (_) => _buildCoverPage(
          chatTitle: chatTitle,
          personaName: persona.name,
          messages: messages,
          primary: primary,
          secondary: secondary,
          bold: bold,
          regular: regular,
        ),
      ),
    );

    // ── Chat pages ───────────────────────────────────────────────────────────
    final totalPages = (messages.length / 15).ceil() + 1;
    for (var i = 0; i < messages.length; i += 15) {
      final chunk = messages.sublist(
        i,
        (i + 15) > messages.length ? messages.length : i + 15,
      );
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.fromLTRB(32, 40, 32, 40),
          build: (_) => _buildChatPage(
            messages: chunk,
            personaName: persona.name,
            primary: primary,
            secondary: secondary,
            pageNum: (i ~/ 15) + 2,
            totalPages: totalPages,
            regular: regular,
            bold: bold,
          ),
        ),
      );
    }

    final bytes = await pdf.save();
    return Uint8List.fromList(bytes);
  }

  // ── Cover Page ─────────────────────────────────────────────────────────────
  static pw.Widget _buildCoverPage({
    required String chatTitle,
    required String personaName,
    required List<Message> messages,
    required PdfColor primary,
    required PdfColor secondary,
    required pw.Font bold,
    required pw.Font regular,
  }) {
    return pw.Stack(
      children: [
        // Dark background
        pw.Positioned.fill(
          child: pw.Container(color: const PdfColor(0.04, 0.04, 0.08)),
        ),

        // Top accent bar
        pw.Positioned(
          top: 0, left: 0, right: 0,
          child: pw.Container(
            height: 5,
            decoration: pw.BoxDecoration(
              gradient: pw.LinearGradient(colors: [primary, secondary]),
            ),
          ),
        ),

        // Main content
        pw.Padding(
          padding: const pw.EdgeInsets.all(56),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.SizedBox(height: 48),

              // App name
              pw.Text('CHATTR',
                  style: pw.TextStyle(
                    font: bold,
                    fontSize: 12,
                    letterSpacing: 6,
                    color: primary,
                  )),

              pw.SizedBox(height: 20),

              // Title
              pw.Text(chatTitle,
                  style: pw.TextStyle(
                    font: bold,
                    fontSize: 36,
                    color: PdfColors.white,
                  )),

              pw.SizedBox(height: 16),

              // Accent line
              pw.Container(width: 56, height: 3, color: primary),

              pw.SizedBox(height: 28),

              // Persona + count badge
              pw.Container(
                padding: const pw.EdgeInsets.symmetric(
                    horizontal: 16, vertical: 10),
                decoration: pw.BoxDecoration(
                  color: _dimColor(primary, 0.12),
                  borderRadius:
                  const pw.BorderRadius.all(pw.Radius.circular(10)),
                  border: pw.Border.all(
                      color: _dimColor(primary, 0.4), width: 0.8),
                ),
                child: pw.Text(
                  '$personaName Persona  |  ${messages.length} messages',
                  style: pw.TextStyle(
                    font: bold,
                    fontSize: 12,
                    color: primary,
                  ),
                ),
              ),

              pw.Spacer(),

              // Stat boxes
              pw.Row(
                children: [
                  _statBox('TOTAL', '${messages.length}', primary, bold, regular),
                  pw.SizedBox(width: 12),
                  _statBox('YOUR MSGS',
                      '${messages.where((m) => m.isUser).length}',
                      secondary, bold, regular),
                  pw.SizedBox(width: 12),
                  _statBox('AI REPLIES',
                      '${messages.where((m) => !m.isUser).length}',
                      primary, bold, regular),
                ],
              ),

              pw.SizedBox(height: 32),

              pw.Divider(
                  color: const PdfColor(1, 1, 1, 0.15), thickness: 0.5),
              pw.SizedBox(height: 10),

              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Generated by Chattr',
                      style: pw.TextStyle(
                          font: regular,
                          fontSize: 9,
                          color: const PdfColor(1, 1, 1, 0.3))),
                  pw.Text(_formatDate(DateTime.now()),
                      style: pw.TextStyle(
                          font: regular,
                          fontSize: 9,
                          color: const PdfColor(1, 1, 1, 0.3))),
                ],
              ),
            ],
          ),
        ),
      ],
    );
  }

  // ── Chat Page ──────────────────────────────────────────────────────────────
  static pw.Widget _buildChatPage({
    required List<Message> messages,
    required String personaName,
    required PdfColor primary,
    required PdfColor secondary,
    required int pageNum,
    required int totalPages,
    required pw.Font regular,
    required pw.Font bold,
  }) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        // Header
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('CHATTR',
                style: pw.TextStyle(
                    font: bold,
                    fontSize: 9,
                    letterSpacing: 3,
                    color: primary)),
            pw.Text('Page $pageNum of $totalPages',
                style: pw.TextStyle(
                    font: regular, fontSize: 9, color: PdfColors.grey)),
          ],
        ),
        pw.SizedBox(height: 4),
        pw.Divider(color: primary, thickness: 0.5),
        pw.SizedBox(height: 14),

        // Messages
        pw.Expanded(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: messages
                .map((msg) => pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 12),
              child: _buildBubble(
                message: msg,
                personaName: personaName,
                primary: primary,
                regular: regular,
                bold: bold,
              ),
            ))
                .toList(),
          ),
        ),
      ],
    );
  }

  // ── Message Bubble ─────────────────────────────────────────────────────────
  static pw.Widget _buildBubble({
    required Message message,
    required String personaName,
    required PdfColor primary,
    required pw.Font regular,
    required pw.Font bold,
  }) {
    final isUser = message.isUser;
    final bgColor = isUser
        ? _dimColor(primary, 0.25)
        : const PdfColor(0.92, 0.92, 0.92);
    final textColor =
    isUser ? PdfColors.white : const PdfColor(0.1, 0.1, 0.1);
    final labelColor = isUser ? primary : PdfColors.grey700;

    return pw.Column(
      crossAxisAlignment: isUser
          ? pw.CrossAxisAlignment.end
          : pw.CrossAxisAlignment.start,
      children: [
        // Sender + time
        pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 3, left: 4, right: 4),
          child: pw.Row(
            mainAxisSize: pw.MainAxisSize.min,
            children: [
              pw.Text(isUser ? 'You' : personaName,
                  style: pw.TextStyle(
                      font: bold, fontSize: 9, color: labelColor)),
              pw.SizedBox(width: 5),
              pw.Text(_formatTime(message.timestamp),
                  style: pw.TextStyle(
                      font: regular,
                      fontSize: 8,
                      color: PdfColors.grey500)),
            ],
          ),
        ),

        // Bubble
        pw.Container(
          constraints: const pw.BoxConstraints(maxWidth: 360),
          padding: const pw.EdgeInsets.symmetric(
              horizontal: 12, vertical: 8),
          decoration: pw.BoxDecoration(
            color: bgColor,
            borderRadius: pw.BorderRadius.only(
              topLeft: const pw.Radius.circular(12),
              topRight: const pw.Radius.circular(12),
              bottomLeft: pw.Radius.circular(isUser ? 12 : 3),
              bottomRight: pw.Radius.circular(isUser ? 3 : 12),
            ),
          ),
          child: pw.Text(
            message.text,
            style: pw.TextStyle(
                font: regular, fontSize: 10, color: textColor),
          ),
        ),
      ],
    );
  }

  // ── Stat Box ───────────────────────────────────────────────────────────────
  static pw.Widget _statBox(
      String label,
      String value,
      PdfColor color,
      pw.Font bold,
      pw.Font regular,
      ) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        color: _dimColor(color, 0.1),
        borderRadius:
        const pw.BorderRadius.all(pw.Radius.circular(10)),
        border: pw.Border.all(
            color: _dimColor(color, 0.35), width: 0.8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(value,
              style: pw.TextStyle(
                  font: bold, fontSize: 24, color: color)),
          pw.SizedBox(height: 3),
          pw.Text(label,
              style: pw.TextStyle(
                font: regular,
                fontSize: 8,
                color: const PdfColor(1, 1, 1, 0.4),
                letterSpacing: 0.8,
              )),
        ],
      ),
    );
  }

  // ── Helpers ────────────────────────────────────────────────────────────────

  // Dim a PdfColor by multiplying channels
  static PdfColor _dimColor(PdfColor c, double factor) =>
      PdfColor(c.red * factor, c.green * factor, c.blue * factor);

  // Flutter Color → PdfColor
  static PdfColor _toPdfColor(Color color) =>
      PdfColor(color.r, color.g, color.b, color.a);

  static String _formatTime(DateTime dt) {
    final h = dt.hour > 12 ? dt.hour - 12 : (dt.hour == 0 ? 12 : dt.hour);
    final m = dt.minute.toString().padLeft(2, '0');
    final period = dt.hour >= 12 ? 'PM' : 'AM';
    return '$h:$m $period';
  }

  static String _formatDate(DateTime dt) {
    const months = [
      'Jan','Feb','Mar','Apr','May','Jun',
      'Jul','Aug','Sep','Oct','Nov','Dec'
    ];
    return '${months[dt.month - 1]} ${dt.day}, ${dt.year}';
  }

  static void _showLoading(BuildContext context) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (_) => const Center(
        child: Card(
          child: Padding(
            padding: EdgeInsets.all(24),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                CircularProgressIndicator(),
                SizedBox(height: 16),
                Text('Generating PDF...'),
              ],
            ),
          ),
        ),
      ),
    );
  }

  static void _showError(BuildContext context, String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: Colors.red,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12)),
      ),
    );
  }
}